// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF642lymjM_NNVicvJpjmRP_8ykgiTLZQ',
    appId: '1:662051709983:web:c8be783307795be6bb212a',
    messagingSenderId: '662051709983',
    projectId: 'gearbox-8c179',
    authDomain: 'gearbox-8c179.firebaseapp.com',
    storageBucket: 'gearbox-8c179.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIASQnd7pcl5w3KnM4N-bqotyZ-ftO8nY',
    appId: '1:662051709983:android:6033b77845400467bb212a',
    messagingSenderId: '662051709983',
    projectId: 'gearbox-8c179',
    storageBucket: 'gearbox-8c179.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_S7M-DyvVlh6IEKwxQcyI0SI3zD_-YE0',
    appId: '1:662051709983:ios:4fa7de3766df0c03bb212a',
    messagingSenderId: '662051709983',
    projectId: 'gearbox-8c179',
    storageBucket: 'gearbox-8c179.appspot.com',
    iosBundleId: 'com.example.gearbox3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_S7M-DyvVlh6IEKwxQcyI0SI3zD_-YE0',
    appId: '1:662051709983:ios:4fa7de3766df0c03bb212a',
    messagingSenderId: '662051709983',
    projectId: 'gearbox-8c179',
    storageBucket: 'gearbox-8c179.appspot.com',
    iosBundleId: 'com.example.gearbox3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF642lymjM_NNVicvJpjmRP_8ykgiTLZQ',
    appId: '1:662051709983:web:e9c018b03b1f2adfbb212a',
    messagingSenderId: '662051709983',
    projectId: 'gearbox-8c179',
    authDomain: 'gearbox-8c179.firebaseapp.com',
    storageBucket: 'gearbox-8c179.appspot.com',
  );
}
